FROM tensorflow/tensorflow:1.15.0-py3

WORKDIR /code

ENV FLASK_APP=app.py FLASK_RUN_HOST=0.0.0.0

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY ./api .

# Define volumes for:
#   - the dataset (used for training),
#   - kidney stone images (uploaded on the API),
#   - kidney stone images (labeled by user to enlarge dataset)
VOLUME /dataset /upload /custom-dataset

EXPOSE 5000

CMD ["flask", "run"]
