FROM python:3.7-slim

WORKDIR /code

ENV FLASK_APP app.py
ENV FLASK_RUN_HOST 0.0.0.0

COPY ./requirements.txt .
RUN pip install -r requirements.txt
    && pip install --ignore-installed --upgrade https://github.com/lakshayg/tensorflow-build/releases/download/tf-1.14-ubuntu18.04-py3.7/tensorflow-1.14.1-cp37-cp37m-linux_x86_64.whl
    # Not sure which tensorflow version we should use
COPY ./api .
EXPOSE 5000
CMD ["flask", "run"]
